[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Build configuration for full-stack app
[build.steps]
install = "npm install && cd client && npm install --legacy-peer-deps"
build = "npm run build"

# Force Node.js version to avoid compatibility issues
[build.environment]
NODE_VERSION = "18" 