[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/test"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Build configuration for full-stack app
[build.steps]
install = "npm install && cd client && npm install --legacy-peer-deps"
build = "npm install && cd client && npm install --legacy-peer-deps && npm run build"

# Use modern Node.js version for updated dependencies
[build.environment]
NODE_VERSION = "20"

[deploy.environment]
NODE_ENV = "production" 